version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 19090:9090
    pid: host
    user: 1001:1001
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-lifecycle' 
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention.time=20d'
      - '--log.level=debug'
    volumes:
        - '/home/ubuntu/prometheus/config:/etc/prometheus'
        - '/home/ubuntu/prometheus/data:/data'
    networks:
      - prometheus-network

  pushgateway:
    container_name: prometheus-pushgateway
    image: prom/pushgateway:latest
    restart: unless-stopped
    ports:
      - 19091:9091
    pid: host
    user: 1001:1001
    command: 
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-lifecycle' 
      - '--log.level=debug'
    volumes:
        - '/home/ubuntu/prometheus/config:/etc/prometheus'
    depends_on:
      - prometheus
    networks:
      - prometheus-network
      

networks:
  prometheus-network:
    driver: bridge

